version: "3"
services:
  app:
    build: .
    volumes:
      - "./src:/app"
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
